### ISSUE TITLE
Vagrant tests should depend on build and actually test the docker image being built.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/docker-hive#16]

**Comment by zhenik** [comment]
Should we include building [hadoop base image](https://github.com/fredrikhgrelland/docker-hadoop)?

test pipeline sequence will be like:
`build base image` ~> `build hive image` ~> `test hive image`

**Comment by zhenik** [comment]
Coupled with #25

**Comment by zhenik** [comment]
TODO:
- [ ] resolve #25 
- [ ] build docker image with github-actions
- [ ] make docker image available on next github-actions step
- [ ] render new image tag for nomad_job using terraform [template_file](https://www.terraform.io/docs/providers/template/d/file.html)
- [ ] run terraform and test against docker container
