### ISSUE TITLE
running the hive-job twice requires canaries. Not enough memory.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/docker-hive#8]

**Comment by zhenik** [comment]
**Does this relevant?**

## Screenshots
![47](https://user-images.githubusercontent.com/15572799/84159083-f1e92600-aa6c-11ea-9499-204a90d62a96.PNG)
![48](https://user-images.githubusercontent.com/15572799/84159108-f9103400-aa6c-11ea-943c-e5e0f7e2a819.PNG)

**Comment by zhenik** [comment]
outdated
